### ISSUE TITLE
include min_rpar and max_rpar in the Euclidean metrics?

### ISSUE THREAD

**Issue by YaoQianli** [rmjarvis/TreeCorr#101]
Hi Mike,

I have been using TreeCorr for several years and it is very helpful! Now I want to explore some more stuff in 3D physical space, but it will require the application of the parallel-distance selection for the pairs, with the "Euclidean" metric. Would you consider including this feature in the next update? 

Thanks,

Ji Yao

**Comment by rmjarvis** [comment]
Probably not the next release (4.1), but I'll put this on the docket for the following one (4.2).

**Comment by YaoQianli** [comment]
That's fantastic! Thank you!

Another thought is, right now TreeCorr can calculate most of the 2-point functions. But it can not do \Delta\Sigma in galaxy-galaxy lensing, since it requires the calculation of distance-differences for each galaxy pairs. This could also be something new, if you are interested.

**Comment by rmjarvis** [comment]
Lots of people have asked for that.  However, I don't think there is anything particular to be gained by using the tree directly, since you have a different calculation to do for each lens.
The two options currently are:
1. Use a single catalog for the sources, but run NGCorrelation on each lens separately (probably with Rlens metric), so you can do the proper conversion from gamma to delta Sigma using the lens redshift.
2. Bin the lenses up into fine redshift slices and do the same thing with each set of lenses that all have basically the same redshift.

**Comment by YaoQianli** [comment]
Ah~~ I see. Very good points! I am a little concerned about the calculation time by doing this... I will give it a try. Thanks!

**Comment by rmjarvis** [comment]
Done in #121.
