### ISSUE TITLE
strange result in three point correlation function calculation 

### ISSUE THREAD

**Issue by murtinauth** [rmjarvis/TreeCorr#110]
I put a dataset through TreeCorr to calculate the three point correlation function used the same min sep, max sep, and nbins as I did for the two point correlation function. Is this expected? I didn't use "u" or "v" parameters since I want equilateral triangles. Do you have any suggestions? 

![treecorr_2pcf_0 0_z_1 0](https://user-images.githubusercontent.com/23534193/86544689-cc213680-bedd-11ea-895f-4e1786fc060a.png)

![three_point1](https://user-images.githubusercontent.com/23534193/86544678-b875d000-bedd-11ea-8f59-a4de9fe856b1.png)

**Comment by rmjarvis** [comment]
You're getting all the triangles here, not just equilateral.  The default behavior of the three-point calculation (as described [here](https://rmjarvis.github.io/TreeCorr/_build/html/correlation3.html)) is to let u range from 0..1 and v range from 0..1 with the same binsize as you are using for the logr bins.  That's why you're getting lots of points at each r.  If you look at the output, you'll see that there are lots of different u and v bins at each r value.

To get just equilateral triangles, you want u near 1 and v near 0.  So use something like min_u=0.9, max_u=1, nubins=1, min_v=0, max_v=0.1, nvbins=1.  Adjust the 0.9 and 0.1 to define how precisely equilateral you want the triangles to be.

Note that there will still be 2 bins for each r, since we distinguish clockwise and counterclockwise orientations for triangles, which are indicated with positive and negative v.  This obviously doesn't matter for equilateral triangles, so you should average the results from the + and - v values for each r.

**Comment by rmjarvis** [comment]
BTW, the u and v values are included in the output, so you can also select the rows with the highest u and lowest v from your existing output to select the equilateral triangles.
e.g.
```
select = data['u_nom'] > 0.9 & np.abs(data['v_nom'] < 0.1)
r = data['meand1'][select]
zeta = data['zeta'][select]
sigma = data['sigma_zeta'][select]
```
This will let you use your current output for now, so you don't need to rerun just yet.  But when you do rerun, setting the min_u, max_u, min_v, max_v as I suggested above will make it a lot faster, since it won't accumulate all the triangles you don't care about.

**Comment by murtinauth** [comment]
THANK YOU! I have been trying to figure out how to manage u and v, but have
been struggling. This module is fabulous!
