### ISSUE TITLE
Use of Patches in discontinuous patches of sky

### ISSUE THREAD

**Issue by TiankeZhuang** [rmjarvis/TreeCorr#114]
Hi, I'm using TreeCorr to perform weak-lensing and clustering signal calculation on the HSC Year 1 data and I am running into a few issues using the Patches tool. 
When I try to run `patch_centers` on the entire data set, it would seem that the points are not divided into patches of similar numbers of galaxies. I have attached below two images, one showing the spacial distribution of the data set and the other showing the spacial distribution of galaxies in each patch. 
I wonder if this is a known issue, and if not, would you have any suggestions on how to customize the patch definition?
Thank you very much!
![patch_all](https://user-images.githubusercontent.com/34909348/93488472-66d1c480-f8d4-11ea-8ce4-ea31163fcff9.png)
![patch](https://user-images.githubusercontent.com/34909348/93488460-63d6d400-f8d4-11ea-92ab-f17f758aa333.png)

**Comment by rmjarvis** [comment]
Interesting.  This is definitely a consequence of HSC having disjoint regions.  The kmeans algorithm works better when the area is all contiguous so the iteration can trade points among the patches to equalize the numbers.  In this case, once the northern patch (say) only has one patch, there's no way to get another patch up there.  The kmeans algorithm (any implementation, not just the one TreeCorr implements) cannot really recover from the initialization only putting one patch center up there.

It does look like it's doing a reasonable job of making relatively equal sized patches *within* each of your disjoint regions at least.  So I can think of three possible solutions.  

1. The first option would be to have treecorr separately make patches in each of your separated regions, manually setting the number of patches in each so that they will have roughly similar numbers of galaxies.  You can then write the patch files for each region to separate files and then combine them by hand into a single file.  You'd have to modify the first column (patch number), since they will each start at 1, but the other columns can be left unchanged.

2. You could skip the the automatic patch generation by the Catalog, but instead use the Field methods directly.  You can see documentation of [run_kmeans](https://rmjarvis.github.io/TreeCorr/_build/html/field.html#treecorr.Field.run_kmeans).  And if you look at the source code for that function, it just calls three functions in turn:
```
centers = self.kmeans_initialize_centers(npatch, init)
self.kmeans_refine_centers(centers, max_iter, tol, alt)
patches = self.kmeans_assign_patches(centers)
return patches, centers
```
So you can replace the initialization step with your own version that makes sure you get an appropriate number of patch centers in each of your disjoint regions.  E.g. make a field for each region, call `field.kmeans_initialize_centers(n)` to get a list of centers for each one.  Then just concatenate these to a single list and call the next two functions on your full field with all the galaxies.  This will run the kmeans algorithm with a better starting point that should preserve the number of patches you end up with in each region.

3. Finally, and probably the easiest if it works, but I'm not sure how well it will work, there are other initialization algorithms implemented already in TreeCorr.  The default is "tree", which works very well for contiguous regions.  But there is also "random", which takes N random galaxies from your catalog, and "kmeans++", which you can read about [here](https://en.wikipedia.org/wiki/K-means%2B%2B).  The TreeCorr docs about this are [here](https://rmjarvis.github.io/TreeCorr/_build/html/field.html#treecorr.Field.kmeans_initialize_centers).  I think it's possible that "kmeans++" will do a much better job at initializing this for you.  It's supposed to have some kind of guarantee about how bad the initialization is allowed to be.  I haven't investigated it too closely though, since for all the (contiguous) geometries I tried, "tree" worked better.  But for your case, I think it's very possible that "kmeans++" will get a better starting point for you.  To use this, simply set `kmeans_init='kmeans++'` when making your Catalog, and it will use this init option when making patches.

**Comment by rmjarvis** [comment]
I hope my above suggestions worked.  As I don't think there is anything in TreeCorr to be done related to this, I'm closing the issue.  Feel free to reopen if you have further questions or think that there is a bug in TreeCorr that needs to be fixed related to this.
