### ISSUE TITLE
compute projected correlation function wp(rp)?

### ISSUE THREAD

**Issue by beckermr** [rmjarvis/TreeCorr#17]
How exactly does the 3d option work, where you specify ra, dec, and r? There seems to be very little documentation. Does it just use the Euclidean distance in 3d? It might be nice to have the option to compute the projected correlation function(s) in the geometry defined by wp(rp).

**Comment by jablazek** [comment]
We discussed this issue at the Ann Arbor DES meeting. To summarize: for some purposes, we want to calculate the correlation function binned by transverse separation (r_p) and line-of-sight separation (Pi) between the pairs: xi(r_p, Pi). This statistic is frequently then projected along the line-of-sight, up to some max projection length, leading to w_p(r_p).

TreeCorr does not currently allow this type of binning, but there is a straightforward way to do it using existing functionality. Divide the catalog into many bins of fixed comoving radial width. These bins should be narrow enough such that the desired projection length is several bins wide. (We haven't yet tested know how many bins are required to avoid losing a significant number of pairs due to bin boundaries. Something like 5-10 should be sufficient. In the limit of infinitely narrow bins, you recover the exact result.) You then combine the correlation functions for all pairs of bins that are separated by less than the desired projection length (using ng.finalize).

Why can this type of accumulation not be done for the NN correlation?

**Comment by jablazek** [comment]
Ignore the previous question about NN correlations.

**Comment by rmjarvis** [comment]
I should correct slightly what I told Jonathan in person yesterday.  

The NN correlation can be accumulated the same way as he described here.  I claimed that it doesn't have a `finalize` function, since there is nothing to do to finalize the calculation.  The number of pairs accumulated is your final answer.  

However, there is actually a `finalize` function for NN, which just finishes the calculation for the meanlogr column.  It is correct that the npairs accumulation is already what you need for NN correlation, so nothing else needs to be done in the finalize step.

Then to combine with the corresponding random calculation, you should use `dd.calculateXi(rr, dr)` (where `dr` is optional).

**Comment by rmjarvis** [comment]
Update: @tmcclintock has now also requested this feature.  He and Eduardo Rozo (who doesn't seem to be on GitHub so I can't @ reference him) suggested that the only thing they would need is to change the metric to compute r_perp for two cells rather than the full 3d distance.  Here is a figure he sent me describing the distance metric he has in mind:

![tangential separation](https://cloud.githubusercontent.com/assets/623887/9537711/b8629184-4d09-11e5-8247-0d0fb62a5c26.png)

Tom suggested just using D in this figure as the metric (aka R_perp or r_p).  This would be quite a lot easier than changing the binning to be in terms of both (r_perp and r_parallel) as I had been thinking would be required.

@beckermr and @jablazek, does this sound like it would work for you?  Are there additional quantities that I should be accumulating in this case, such as <(r1+r2)/2> or <r_parallel> for instance?

**Comment by rmjarvis** [comment]
This is now merged into master.  The syntax I settled on is
```
nn.process(cat, metric='Rperp')
nn.process(cat1, cat2, metric='Rperp')
```
Then the distances between two cells is defined for two points at distance r1, r2 from Earth as follows:
Define d = the normal Euclidean distance.  
Rparallel = |r1-r2|
Rperp^2 = d^2 - Rparallel^2.

**Comment by jablazek** [comment]
@rmjarvis - Sorry for the delay in responding. What you have implemented should take care of what I need. Thanks!

**Comment by rmjarvis** [comment]
Great.  Thanks.  I should be ready with 3.2 within a week or so, which will include this.  I'm trying to crank through a bunch of the feature requests that had been accumulating here.  :)

**Comment by beckermr** [comment]
Looks great!
