### ISSUE TITLE
Maximum separation

### ISSUE THREAD

**Issue by svw26** [rmjarvis/TreeCorr#39]
Hello Mike

Hope you are well, and thank you for making the TreeCorr package publicly available.

I was wondering whether there is an inbuilt restriction on the maximum value that the parameter max_sep can be(!). This is because I am using an all-sky survey, and so expect that the maximum separation is 180 degrees (i.e. directly-opposite sides of the celestial sphere). However when I use this I find that there is a cut off, in the number of pairs counted, at 128 degrees. Yet there are clearly pairs of objects that satisfy a separation between 128 and 180 degrees. I thought I would test it using a smaller region, defined over the equator from RA=135 deg to RA=225 deg (-20 < Dec/deg <20), setting max_sep to 90 deg. npairs (for the data-points) remains non-zero until 81.4 deg, yet I can pick a pair of objects whose separation is 88.1 deg.

Out of curiosity, what is the step used to store the ra and dec values in the catalogues for TreeCorr? As I had specified units='deg', I was puzzled that printing each of the cat_data.ra[i] and cat_data.dec[i] values showed that they did not match up to the input ra and dec. Instead, each needed to be scaled up by a factor of just over 57, and there seemed to be a larger offset as RA increased...

Hope to hear from you soon.
Many thanks,
Sarah

**Comment by rmjarvis** [comment]
A couple things here.  First, the internal units for all angles in TreeCorr is radians, so accessing `cat_data.ra[i]` and `cat_data_dec[i]` will show the value in radians, not degrees.  That explains the factor of 57 you saw.

The bigger issue you are seeing is that the reported separations for the final correlation function are technically the chord distances across the unit sphere rather than the great circle angle.  cf. the [documentation of the `Euclidean` metric](http://rmjarvis.github.io/TreeCorr/html/nn.html#treecorr.NNCorrelation.process), although I admit the documentation about this fact is probably too light currently.

For small angles, they are basically equivalent, so it doesn't make much difference.  But with angles of 90 or 180 degrees, it makes a bit difference.  An angle of 180 degrees is pi radians.  But the chord distance is only 2 (the diameter).  If you ask for this in degrees, it will multiply by 180/pi to get 115, not 180.  With the binning, I think this is why it looked like a maximum of 128 degrees.  Probably it was really a maximum of 115 "degrees", which means a maximum of 2 for the chord distances.

The reason for this is that it is much faster to compute distances in Euclidean coordinates rather than in spherical coordinates, so we put all the points on the unit sphere and then use Euclidean separations for everything.  I should probably change this so that it at least converts back to the great circle distance at the end, but I haven't yet, since most people are using separations < 10 degrees where it doesn't make a big difference.

In the meanwhile, you can convert the reported distances yourself using the formula:

    r_GC = 2 * math.asin(0.5 * r_chord)

where both `r_GC` and `r_chord` are in radians.

**Comment by svw26** [comment]
Many thanks, Mike! That makes sense. (And can't believe I didn't recognise
where the factor 57 came from... oh well)

-------------------------------------------------------------------------------

Dr Sarah White

International Centre for Radio Astronomy Research (ICRAR)


*Email:* sarah.white@icrar.org

*Postal address:* Curtin University,

GPO Box U1987, Perth, WA, 6845

*Office address:* Room 166, Brodie-Hall Building (610),

1 Turner Avenue, Technology Park, Bentley, WA, 6102

*Tel:* +61 8 9266 9245

*Fax:* +61 8 9266 9246

**Comment by rmjarvis** [comment]
I made some updates in response to this, which will be included in version 3.3:

1. All the attributes that have units of distance will be in the requested sep_units throughout, including min_sep, max_sep, logr, meanr, meanlogr.  This seems more intuitive.  The versions that I need in various places to be in radians are now in "hidden" attributes like `_min_sep` and `_max_sep`.
2. For the normal spherical geometry case where I use the chord distances for increased speed over doing the trig functions, I now update the distances at the end to be the real great circle angular distances.  i.e. it now does this equation to the `meanr` and `meanlogr` values at the end of the process function:

    r_GC = 2 * math.asin(0.5 * r_chord)

to get back to real angles, rather than the weird hybrid thing it used to do.

3. I also added a new metric called "Arc" which does the (slower) trig functions to get real great circle distances all along the way, rather than correct the angles at the end.  For most purposes, you'll probably want to stick with the faster version, but this will let you compare the two methods to see whether the chord method is leading to any inaccuracies for your application.

Please reopen if you have any further questions or comments about these changes.  And thanks again for the bug report.
