### ISSUE TITLE
Support linear bin spacing

### ISSUE THREAD

**Issue by rmjarvis** [rmjarvis/TreeCorr#5]
Currently, the binning in separation is done in log(r), which is usually appropriate given the kinds of applications we usually have in astronomy.  However, some people have asked about linear spacing instead.  I think it would require a bit of thinking about how this might change some of the underlying correlation code, since the log spacing is kind of hard-coded into that.  But it's worth looking into.

If this is important to you, please chime in below and describe your use case.  Otherwise, this will likely fall off my radar...

**Comment by wagoner47** [comment]
I am trying to use the code to compute 3D correlation functions. I'm currently trying to make sure the rest of my code is working by comparing to results in literature for SDSS galaxies. However, all of the papers I have been using as references are binned in linear space. It would be nice to either be able to use linear binning or else input an array or function for the bin_size so that I can make sure it is properly spaced linearly even while the code uses log separation.

**Comment by elvinpoole** [comment]
I am computing w(theta) in 2d and it would be great to use linear binning in theta. As above, the literature seems to often use linear binning for this case, so it would be useful for comparisons. thanks

**Comment by rmjarvis** [comment]
Thanks for the +1 Jack.  I have an idea about how to implement this, but it's a pretty big reworking of the back end code.  I'm hoping to get to this issue in the next couple months...

**Comment by cs0uth** [comment]
hey there @rmjarvis,  no news from linear binning? it would be great if you could add it as soon as possible....people are hanging here!!

**Comment by rmjarvis** [comment]
Hanging?  Meaning that there is some science that you are unable to do with logarithmic binning?  

I'm curious what that would be and why you can't just use a fairly small bin size over the range you are interested in.

I do plan to get to this.  Probably before DES year 3 analysis starts, since the way I plan to implement it I think should also speed up the bin_slop < 1 mode that we usually use in DES.  But a number of other projects are still higher priority than this.

**Comment by cs0uth** [comment]
No, I meant since almost all graphs people use are in linear bins, and it's fairly easy to visually see in count-count correlation function features like BAO peak, it would be nice to have linear binning that doesn't relatively "smooth out" this peak.

for the work i'm doing it doesn't matter that much if i have linear or logarithmic binning, i can do it by 
using relatively small bin sizes in logarithmic scale.

I think having linear binning option would be great to implement.

**Comment by gvalogia** [comment]
Hello,

I am using the code to calculate 3d correlation functions from simulation data.

I want to use these results to study both the BAO scales, as well as smaller ones down to 1-10 Mpc/h.
If I use logarithmic binning, having enough bins to study the BAO peak properly comes at the expense of using too many bins in the smaller scales, which makes the data there noisy. For this reason, linear spacing would be preferred for this and I've noticed that this is what people use in the literature. 

Of course playing around with the range and bin size can give me something close to what I would prefer, but I believe that having the linear spacing option would help in such cases. (I understand that it may be hard to implement though)

Great code by the way, thanks for sharing!

**Comment by rmjarvis** [comment]
Done (finally!) in PR #77.  Will be included in v3.4.
