### ISSUE TITLE
Feature Request: Overloading -= and multiplying NNCorrelations

### ISSUE THREAD

**Issue by tmcclintock** [rmjarvis/TreeCorr#51]
At present, the following code works:
```
NN1 = NNCorrelation(config)
NN1 += NN2
```
where DD is some other NN correlation object. This works because the "+=" operator (__iadd__) has been overloaded starting on line 256 of nncorrelation.py. However, when creating jackknifes this is not all we need.

To do jackknifing intelligently, we need to be able to have an overloaded "-=" and be able to multiply correlations. Essentially, we also need:
```
NN1 -= NN2
NN1 += 0.5 * NN2
```
This amounts to implementing functions very similar to __iadd__. If you want I do this myself and issue a pull request.

**Comment by rmjarvis** [comment]
I think you want to be doing this just on the `npairs` or `weight` attribute.  Not the `NNCorrelation` object as a whole.

The point of the `+=` operation in treecorr is not for this kind of thing.  Rather it is to allow for distributing the processing across multiple machines.  The idea is that you'd run `process_auto` or `process_cross` on some subset of the data over multiple jobs so that in total, you've done everything.  But then you still need to add it all together into a single correlation object and then call `finalize` to finish the calculation.  These steps would be done as an afterburner on a single machine (presumably reading in the various results from files).

For `NNCorrelation`, `finalize` doesn't do a whole lot, so I can see how this wouldn't be particularly obvious in that case.  But for every other kind of correlation, it divides by the total weight in each bin.  (`NNCorrelation` also does that for `meanr` and `meanlogr`, but that's it.)

So I don't think `__isub__` or `__mul__` make sense given this intended usage of `__iadd__`.  Indeed, what would you want to do to the `meanr` and `meanlogr` arrays?  Subtracting or multiplying them don't make a whole lot of sense.  Rather, I think for doing jackknife calculations, you would only want to do these operations on the `npairs` (or `weight`) attribute, which is a numpy array that already has these operations defined.  For other kinds of correlations, you typically work with the `xi` or `xip`/`xim` attributes.

**Comment by tmcclintock** [comment]
That's fair. I figured it would be easier for implementing jackknifing if we could just add/subtract/multiply NNCorrelations when doing the jackknifing than actually worrying about each array individually.

In fact, in my own implementation of jackknifing I do just that - add the arrays, however it would have saved tens of lines of code if I could have performed the operations on the NNCorrelation objects themselves. I understand if this is against the intended design, though.

**Comment by rmjarvis** [comment]
I guess I don't understand why there would be more lines of code.  The way to do the lines you gave above would be
```
NN1 = NNCorrelation(config)
# ...
NN1.npairs += NN2.npairs
NN1.npairs -= NN2.npairs
NN1.npairs += 0.5 * NN2.npairs
```
This is the same number of lines, and only does the calculations that you actually care about without doing something arbitrary and probably wrong to the other arrays in `NN1`.
