### ISSUE TITLE
Metrics for Phase Space Correlations

### ISSUE THREAD

**Issue by ltlancas** [rmjarvis/TreeCorr#55]
Hi,
  This certainly qualifies as a request for a new feature but I'd love to help implement it as well.  I'm trying to look in to correlations on all of phase space (position and velocity/proper motion) and as such I need a metric that can be defined on all of phase space.  There are obviously many ways to do this, and would love to discuss which might be best. I think this feature would be particularly useful in studies of the galactic structure, especially in the era of Gaia.

Let me know what you think!
 - Lachlan Lancaster

**Comment by rmjarvis** [comment]
I think it's not too hard to get velocities into TreeCorr as a quantity to be correlated.  Right now we just have counts (N) scalars (K) and spinors (G), since these are the things we normally need in weak lensing and large scale structure.

But I've thought some about adding vectors, for which I'd suggest the indicator letter V.  In 2D, these would work a lot like spinors, but with exp(i phi) rotation rather than exp(2i phi).  And I think once you project the two vectors relative to the line joining them, the quantities you care about are

    xi+ = v1x * v2x + v1y * v2y
    xi- = v1x * v2x - v1y * v2y

much like xi+, xi- for GG correlations.  There are also two cross terms, which in the complex formulation come out as the imaginary parts of the above quantities:

    xi+_im = v1x * v2y + v1y * v2x
    xi-_im = v1x * v2y - v1y * v2x

Both of these latter two numbers have expectation zero under normal symmetry assumptions, so they are usually not particularly interesting.

For 3D vectors, I'm not sure, but by analogy, I'd imagine that you'd probably care about

    xi+ = v1x * v2x + v1y * v2y + v1z * v2z

After that I guess there are 8 others, but I'm not sure which linear combinations are interesting.  Probably most of them have expectation zero under reasonable symmetry assumptions.

So is this the kind of thing you were thinking about?  Correlate V with V, N with V, and N with N?  

Or did you really mean that you wanted the underlying metric to include the velocities?  i.e. just NN correlations, but where distances were in 6 dimensions somehow?  This latter scenario seems problematic to me, since I'm not sure how to calculate a single "distance" for two objects that are separated by 15 Mpc in space and have delta V = 230 km/s.  

It seems to me that it would be more useful to include the velocity as a thing to be correlated rather than as part of the metric.

**Comment by ltlancas** [comment]
Hi Michael,

  Thanks for the quick response! Your first points are interesting but unfortunately I did really mean the last point that you made, about including the velocities in terms of a metric on the whole of phase space.   The issue you point out is exactly the problem with a metric of this sort, but there should be ways of getting around this by creating a dimensionless metric based on dividing both the position and velocity distributions by some characteristic scales.  I think that this would make TreeCorr particularly useful for studies involving the structure of the Milky Way.

**Comment by rmjarvis** [comment]
You would really want a single "distance" definition for two objects based on both the physical separation and the difference in velocities?  That seems rather incoherent to me.  E.g. you would put into the same bin a pair with ds = 15 Mpc and dv = 230 km/s and a pair with ds = 30 Mpc and dv = 115 km/s.  Are these two pairs really equivalent in any meaningful sense?

I guess if you could make a science case for this, I might consider it, but at the moment I'm not particularly inclined to write code that doesn't seem (to me) to have any direct application.

On the other hand, if you'd like to take a stab at it and submit a pull request, I'll take a look.

**Comment by ltlancas** [comment]
Yes I would! I know it seems strange, but there are many reasons why you would want a metric on the full phase space.  The example you give would indeed "make sense" if you had a physical reason for setting the scale of the system's size at 1 Mpc and the system's velocity at 1 km/s. To see a science case for this see:

Helmi, White, and Springel 2003: https://arxiv.org/pdf/astro-ph/0208041.pdf
Ascasibar and Binney 2008: https://arxiv.org/pdf/astro-ph/0409233.pdf

  As you can see in the intro to Ascasibar and Binney, the only problem is (as you point out) having a realtionship between the units, which (in principle) can be physically motivated. I will take a stab at it first though when I get the chance, I totally understand if this isn't a top priority.

**Comment by rmjarvis** [comment]
I'm closing this due to lack of follow-up.  Feel free to reopen (or make a PR) if you think there is something useful that could be added to TreeCorr related to this.
