### ISSUE TITLE
Is fitsio dependency optional?

### ISSUE THREAD

**Issue by wmwv** [rmjarvis/TreeCorr#57]
I have two related questions/requests:

1. Can the `fitsio` dependency be made optional?
2. Could the `fitsio` dependency be made to load either `fitsio` or `astropy.io.fits`?

The specific use case is adding TreeCorr into the LSST DM validation dependency tree (specifically `validate_drp`).  

Thanks for the great package!

**Comment by wmwv** [comment]
Ah, so I see the 3.2->3.3 intentionally made `fitsio` a required dependency and I'm kind of asking for that to be undone.

https://github.com/rmjarvis/TreeCorr/blob/a664f412c88d3fdeb257158f02a417640bccf182/CHANGELOG.rst

**Comment by timj** [comment]
There's a difference between `fitsio` is mandatory if you intend to read FITS files vs `fitsio` is mandatory even if you never intend to open a FITS file.

**Comment by rmjarvis** [comment]
It used to be optional, but I zotted the pyfits code a while back, since it is so problematic.  IMO, everyone should be using fitsio rather than astropy for all their fits I/O.  It is far more stable, faster, and has better memory management.

In GalSim, we have workarounds for all the bugs we've found in astropy.io.fits so far, but more keep cropping up from time to time, and I'm not particularly interested in jumping through similar hoops here as well.

But I suppose I could make it optional in the sense that Tim suggests.  Where it would only import fitsio if you are actually trying to open fits files.

**Comment by rmjarvis** [comment]
BTW, I'm curious -- why is the fitsio dependency a hardship?  It is pip installable, so it should be fairly painless as dependencies go.

**Comment by wmwv** [comment]
Because the LSST DM stack doesn't use `pip` to install Python packages.

**Comment by wmwv** [comment]
I agree with the suggestion to make it optional.  And I agree that the person who actually wanted to use the FITS I/O functionality probably does care about the performance.

But perhaps skipping the read/write test should be implemented as an option to the install?  I.e., most users who `pip install treecorr` also wanted `fitsio` from `pip install`, but specific users who for various build tooling reasons who do not and are not using `pip install` might install and choose to skip the read/write test.
