### ISSUE TITLE
Pandas 0.19+ with Python 2.7?

### ISSUE THREAD

**Issue by kadrlica** [rmjarvis/TreeCorr#59]
From the `setup.py` I see that someone was ["Getting weird errors with [pandas] 0.19 on python 2.7"](https://github.com/rmjarvis/TreeCorr/blob/cfb5a155145835f6f0f1989ba10e0bb25b56229f/setup.py#L449). Any idea if these "weird errors" persist for pandas 0.19.2? I'd like to install treecorr into an environment that relies on a newer version of pandas.

**Comment by rmjarvis** [comment]
I don't remember now what that was about.  I'll look into it and see if depending on "pandas >= 0.19.2" is ok.

**Comment by rmjarvis** [comment]
It looks like it's fine now.  I think the problem was that they had pushed their beta release of 0.19 (0.19.0rc1) to PyPy, and it was kind of [broken](https://travis-ci.org/rmjarvis/TreeCorr/jobs/160712008).  It seems that they [fixed](https://travis-ci.org/rmjarvis/TreeCorr/jobs/221488647) the problem sometime between that and 0.19.2, so I'll go ahead and cut a release that doesn't have the `pandas==0.18` restriction.

**Comment by rmjarvis** [comment]
Version 3.3.7 no longer has this restriction.

**Comment by kadrlica** [comment]
Thanks. I've built v3.3.7 with pandas 0.19.2 and will let you know if any issues pop up.
