### ISSUE TITLE
Individual Correlation Functions 

### ISSUE THREAD

**Issue by vdemchenko3** [rmjarvis/TreeCorr#60]
Hello,

I was wondering if there is a way to output each individual measurement (NGcorrelation in my case) per lens?  I'd like to stack the measurements by normalizing each individual GGL signal to a unique value.

Thanks!

**Comment by rmjarvis** [comment]
Not sure exactly what you mean by "each individual GGL signal".  If you mean each lens-source pair, then there's not much point in using a tree code -- you're just doing the brute force calculation.  If you mean the tangential shear signal around each lens separately, then sure -- just run the calculation separately for each lens using lens catalogs with a single position at at time.  Then do what you want with the output.

**Comment by vdemchenko3** [comment]
Hey Mike,

Thanks for the quick response!  Yea I'm looking for the tangential shear around each lens separately and I can run the calculation for each individual lens, but when I loop over my lenses and save the shears in a dictionary, I run into a memory issue after 15 or so lenses and my code gets killed.  I guess I was wondering if Treecorr stores each tangential shear somewhere that can be accessed without me looping over each lens.

**Comment by rmjarvis** [comment]
No, because that's not something that TreeCorr ever calculates.  The internal code does not do each lens separately and then add them up.  it accumulates everything at once.

It sounds to me though that you just need to fix your memory handling.  It sounds like you are possibly making a new source catalog each time, which is unnecessary.  That would be where most of the memory use would be.  Just make a new lens catalog and keep the existing source catalog to pass to `process`.

**Comment by vdemchenko3** [comment]
Hey Mike,

Ah I see.  Yea so the only things in my loop at NGCorrelation and process and I have a dictionary of lens catalogs, but what I can try is to just generate the lens catalog on the fly and not store it.

**Comment by rmjarvis** [comment]
The lens catalogs shouldn't be large.  

If you're making a new NGCorrelation object each time, that might also be the issue.  Particularly if you use different min_sep/max_sep values (or in general different binning choices).  Then is might need to make a new tree for the source objects (which is where all the memory usage is) for each different lens.

The catalogs cache any trees they build, since typical use cases can access the trees multiple times, so this saves the build step from being called repeatedly (however, cf. Issue #53).  If you are asking it to make different trees each time (because of different binning options), then this could be what is blowing up your memory use.

So I think the solution is either to use the same binning for all lenses (which may not be convenient for your use case) or to manually clear the cache each time
```
source_catalog.gfields.clear()
```

BTW, the proposal in Issue #53 would be to swap the default behavior to **not** cache, but let this be an optimization that users could turn on if it is helpful for their particular use case.  It sounds like your use case is another vote in preference for this change.

**Comment by vdemchenko3** [comment]
Yes that is the issue indeed then.  Since I change my max_sep for each lens, I call NGCorrelation each time, which eats up my memory.  I'll use the suggestion to manually clear the cache and that should work!  Thank you!

**Comment by rmjarvis** [comment]
The caching fix is done on master now (via #80).  This feature will be included in version 3.4.
