### ISSUE TITLE
Pairing method for metric='Arc'

### ISSUE THREAD

**Issue by YaoQianli** [rmjarvis/TreeCorr#61]
Hi Dr Jarvis,

Is there a way to select pairing distances along line-of-sight for metric='Arc'? I see that for metric='Arc', we can not use min_rpar and max_rpar. Also the catalog can not contain the r coordinate. Is there a clever trick that can accomplish this goal? Or can it be done easily by modifying the code?

I want to use TreeCorr on photo-z catalogs, and because photo-z is messy, I need to add some selection rules for pairing.

Best,
Ji Yao

**Comment by rmjarvis** [comment]
No.  The whole point of `Arc` is that it treats all the points as being collapsed onto the unit sphere and only considers the separations along great circles of that sphere.

The two things that are usually done when using photometric redshifts are
1. Define some modest number of photo-z bins and compute the auto- and cross-correlations among the various bins.  Especially because photo-zs are generally not super accurate, this lets you just calibrate the overall N(z) within each bin, which is generally much more reliable than trusting each individual photo-z estimate.
2. Give all your objects a full 3D position (ra, dec, r) and use one of the metrics that use physical distances, rather than angular separation.  In TreeCorr, the options are currently `Rlens`, `Rperp` and `Euclidean`.  The former two allow for the `min_rpar` and `max_rpar` parameters.  The third does not.

If neither of these suffice for your science case, you could slice your catalog into many shells in redshift and use Arc for the cross-correlations between shells that fit your rpar criterion.  TreeCorr would still be fairly efficient doing things that way, but there is currently no option for TreeCorr to do that for you.

**Comment by YaoQianli** [comment]
What I want to do is to correlate, for example the shape with galaxy, only when `z^G < z^g` so that the object with shape is closer to us. I tried to do this using `Rprep`, but considering I still want the correlation in the angular `theta` space, and using `theta = r_perp / r_para` is not very precise as `r_para` is not given by TreeCorr, so that I can only estimate it with the mean value for all the objects in a photo-z bin. But I guess this is the fastest method I can use. Is there a better way?

**Comment by rmjarvis** [comment]
The usual way to do what you are doing is what I described as option 1 above.  Use a nearby redshift bin for the lenses and a more distant redshift bin for the sources.  Then correlate everything in the foreground with everything in the background, and you'll have zG < zg for all pairs.

In particular, this has a well-defined theoretical prediction for the signal, which you need in order to do anything useful with the measurement.  It would be much harder to get an accurate prediction for the measurement you are proposing where you take all sources in the background of any lens, especially considering the sample variance in the distribution of lenses and the uncertainties in the photo-zs.

**Comment by YaoQianli** [comment]
Thank you very much for the explanation! But I probably should have mention that I want to do this kind of pairing within the same tomographic bin to see the effect of photo-z, so the selection of `zG<zg` is necessary. I will try to use another metric to have a look.

Thanks again for the help!

**Comment by rmjarvis** [comment]
Done in PR #77.  Will be included in v3.4.
