### ISSUE TITLE
Using Healpix Map

### ISSUE THREAD

**Issue by bnuastro** [rmjarvis/TreeCorr#64]
Dear TreeCorr Team,
I am trying to compute the auto-/cross- correlation functions w.r.t the separation \theta.
One of my data is in healpix format (Nside=1024),  which is similar to CMB temperature maps. 
How can I  use them in TreeCorr?
I test the examples you offered here, founding that they are all catlog/kappa field give (ra,dec). While for my healpix maps, I just have pixile ID.

One idea is the convert healpix pixiles into (ra,dec) under its Nside parameter (After Masking), and then using TreeCorr... Is that right?

However, this may suffer from griding/masking effect.  Maybe the ra dec are not very correct?

Thank you!

**Comment by rmjarvis** [comment]
Yes, you should convert the healpix pixels to Ra/Dec values.  But be careful about it, since if you just take the central points of each pixel you can indeed get spurious effects in the 2pt correlation because of grid effects.  The usual trick that people use to avoid this is to spread the data among random positions within the healpix pixel.

For instance, for counts data, you can divide the total N points for a pixel by 10 and select 10 random points within the pixel.  For scalar data (e.g. kappa or shear), you can just take the mean value, but place it at 10 random locations in the pixel.

Depending on the size of your catalog, you might be able to get away with just keeping one point per healpix pixel, but choose the single location at random from within the pixel.  That should remove the dominant pixelization effects, but might still show spurious effects at small separation.

**Comment by bnuastro** [comment]
Thank you! 
Best

**Comment by yuanshuoastro** [comment]
Dear all,
Thanks for your previous discussions.
I am meeting a similar one.
When working on cross-correlation from galaxy data("N" in treecorr) and CMB map (scalar, like "temperature", may be regarded as  "K" in treecorr), we need build random data to build a Landy's estimatiors.

I know for galaxy catalog, just build uniform points located at RA DEC with the same total number as what is in read catalog. 

However, how to make random mock for CMB temperature map?  Just made a random number in uniform  distribution located on the pixel grids to mock the temperature values ?

Thanks!
Best,

**Comment by rmjarvis** [comment]
No need.  You only need randoms for counts.  i.e. the N part of the correlation in TreeCorr.  K and G are already scalar fields, so there isn't any correction required.  You only need randoms for delta ~= (D-R)/R as an estimator of the density field.
