### ISSUE TITLE
Log source-lens pairs

### ISSUE THREAD

**Issue by vargatn** [rmjarvis/TreeCorr#67]
Hi Mike,

Is there a way to log a *representative* sample of source lens pairs for each radial bin? This is achieved with minor modifications in Erin's *xshear* code, but for Y3 lensing we would like to do something similar with TreeCorr.

(We need these source-lens pairs to do further post-processing and calculate the cluster memeber contamination rate.)

Cheers
Tamas

**Comment by matroxel** [comment]
This is also useful for model prediction. We'd really like to know the distribution of (a random/representative subset of) pairs within an angular bin. 

In practice this would mean for each object in the pair (lenses in the case of cluster/gg lensing), selecting a random N pairs (N could be relatively small) of objects and returning that linking information (from the tree) along with the actual separation of the pair.

**Comment by rmjarvis** [comment]
I still have a few questions about what you want here:

1. Do you want background objects for each foreground object separately (i.e. N sources for each lens) or pairs selected over the whole sample of lenses and sources (i.e. N lens-source pairs).

2. What information do you want about the pairs?  Is just the ID from the input catalog sufficient?  And I guess you said the exact separation distance.  Anything else required?

3. Any suggestion for the API of this feature?

**Comment by rmjarvis** [comment]
@vargatn @matroxel I'm working on implementing this, and I have a question.  

Is it acceptable if the number of index pairs returned is not deterministic?  I.e. If you request 100 pairs, you might get 90 or 105 or some other number drawn from a Poisson distribution with expectation 100.

The reason I ask is that the only efficient way I have thought of to do this so far is to have it go through the same calculation as normal, but with some small probability (N_target / N_total_pairs) add the pair of indices to the output array.  This would yield a Poisson process for the number of index pairs returned, with the given target as the expectation value.

**Comment by rmjarvis** [comment]
Never mind.  I figured out a way to do it efficiently with a set number of output indices.

**Comment by rmjarvis** [comment]
Done in PR #82.  

The syntax is to get a random sample of `N` pairs from the `b` bin of a correlation function is as follows:
```
gg = treecorr.GGCorrelation(...)
gg.process(cat1, cat2)
i1, i2, sep = gg.sample_pairs(N, cat1, cat2,
                                  min_sep=gg.left_edges[b], max_sep=gg.right_edges[b])
```
The return values are:
* `i1` are the indices in `cat1` of each pair.
* `i2` are the indices in `cat2` of each pair.
* `sep` is the separation of the cells in the tree where this pair was deemed to fall into the given range, given the `bin_slop` of the correlation function.

There is no requirement that the min/max sep given to `sample_pairs` be the edges of one of the bins of the underlying correlation though.  You can provide a larger or smaller range if you want.

Note that the returned separations are not necessarily the real separations of the pairs of objects.  Rather they are the separations of the cells where any calculations would have happened when performing the correlation function.  I suspect this will normally be the more relevant value you would want here, especially since given the indices you could calculation the real separation of these particular points yourself, and the comparison between the two values could be worthwhile.

Let me know if this seems to do everything you need, or if there is anything else you would want from this functionality.
