### ISSUE TITLE
Enable 2d binning to compute anisotropic correlation function

### ISSUE THREAD

**Issue by rmjarvis** [rmjarvis/TreeCorr#70]
@PFLeget wants to use TreeCorr to more quickly compute anisotropic correlations functions.

I propose that we add a new Metric call TwoD that would bin in x,y rather than r.

We are working on this at the LSSTDESC hack day at CMU.

**Comment by PFLeget** [comment]
[2pcf_treecorr.pdf](https://github.com/rmjarvis/TreeCorr/files/2237098/2pcf_treecorr.pdf)
[2pcf.pdf](https://github.com/rmjarvis/TreeCorr/files/2237099/2pcf.pdf)

**Comment by PFLeget** [comment]
![2pcf_treecorr](https://user-images.githubusercontent.com/15455475/43344351-638ee054-91b7-11e8-8198-2eb08c3fa6da.png)
![2pcf](https://user-images.githubusercontent.com/15455475/43344365-72f01aea-91b7-11e8-98e1-bd3e36afeeb2.png)

**Comment by rmjarvis** [comment]
Looks like I messed up the centering of the bin array.  The treecorr version has the 2x2 square in the center rather than 1x1.  And nothing on the right/bottom sides.  So I probably have a rounding mistake in the way I calculate which bin to drop things in.

**Comment by rmjarvis** [comment]
The other bit that needs work is to handle the auto-correlation case where we were missing the upper left quadrant.  For that, I think we just need to add a 180 degree rotated version to effectively count all the pairs in both orderings.  So that needs to be a new bit of code at the end of the process_auto function.

**Comment by rmjarvis** [comment]
And, just to be complete, I'll remind myself now that I only added code in the Python layer to KKCorrelation so far.  So once that's working, I need to copy those changes over to the other 2pt functions.  
We can skip doing this metric for 3-pt, but we might need to add an error check to make sure things are handled gracefully if the user tries to use metric=TwoD with a 3pt calculation.

**Comment by PFLeget** [comment]
I did some simple test on speed efficiency of the TwoD metric and without playing with the bin_slop param (I set it to 0), and this is already amazing (I put the plot in the discussion). The typical range that I am working on for the moment is between 10,000 and 20,000 stars, so this is really efficient (~ 3 order of magnitude).

**Comment by PFLeget** [comment]
![time_computing_twod](https://user-images.githubusercontent.com/15455475/43806710-f93b4c00-9a59-11e8-97f3-8d5ede5cd111.png)

**Comment by PFLeget** [comment]
The last problem is the grid where is computed the anisotropic 2-point correlation function, because the central bin is not compute from what I saw (like you referred in your previous post). I put an example within the discussion where it is possible to see that in the case of TreeCorr, the central bin is not computed in comparaison of the brut force. So when I am computing the residual, they are not equal but this is due to misalignment.
(I added anisotropy in the simulation)
![figure_1](https://user-images.githubusercontent.com/15455475/43806748-1eec88d8-9a5a-11e8-80e0-7e2011f0f273.png)
![figure_2](https://user-images.githubusercontent.com/15455475/43806752-242f20b2-9a5a-11e8-9397-f498757f9cc7.png)
![figure_3](https://user-images.githubusercontent.com/15455475/43806755-27884b58-9a5a-11e8-9aff-fc97e20f3b3a.png)

**Comment by rmjarvis** [comment]
I fixed the central pixel issue.  It was just a matter of rounding to the nearest integer, rather than (implicitly) using floor.  I also made a couple other tweaks to the test to get it to pass.  The two results agree to 1.e-7 now over the range where they both have measurements.

There's still more to do on this, but this is probably already close to what you need for tests of the Piff GP stuff.  Amazing that it is so fast even with binslop = 0.  I would have expected maybe a factor of a few faster than the numpy function.  But three orders of magnitude is pretty incredible.  

That probably means it's fine to just use binslop=0 and not bother investigating how high you can raise it, but if you want to try something like 0.01, I'd expect those results to be essentially indistinguishable from binslop=0, but maybe noticeably faster still.

**Comment by PierreAstier** [comment]
For the 2d case metric, the C++ BinnedCorr2 constructor is called with nbins=10 instead of 21**2. If one never uses the copy constructor (and assertions are off), everything goes fine because the histograms are allocated in python with the proper size. If one uses the BinnedCorr2 copy constructor, distasters happen, because histograms copies are way too short. It seems that replacing self.nbins by self._nbins in treecorr/binnedcoor2.py line 91 may solve the issue, but I am by no means sure.

**Comment by rmjarvis** [comment]
Sorry.  I was having trouble reproducing this, and then I realized that I had a local version that has already fixed this bug.  So I pushed it to github.

As part of that, I also rebased the branch onto master rather than releases/3.3 where it had been based.  So this means that you should now do the following to sync up:
```
git checkout twod  # if you're not already on it.
git fetch
git reset --hard origin/twod
```

**Comment by PierreAstier** [comment]
Thanks ! Seems better.

**Comment by rmjarvis** [comment]
Done.  Via PR #76.
