### ISSUE TITLE
Feature request: correlation of vector quantities

### ISSUE THREAD

**Issue by smsharma** [rmjarvis/TreeCorr#81]
It is currently possible to use TreeCorr to compute the correlation functions of a scalar quantity (using kappa as proxy) as well as the shear, defined through g1 and g2. Would it be possible to compute the correlation function(s) of vector (either 2D or 3D) quantities?

My specific use case involves calculating the 2-point correlation functions of velocity vectors of stars in our Galaxy.

Thank you!

**Comment by rmjarvis** [comment]
Can I assume that you'd want the vectors projected onto the line joining them, like we do in shear correlations?  

Then once you've done that, do you have an idea of what combinations you want to accumulate.  For shear, we accumulate <g1 g2*> and <g1 g2> where the (complex) shears have been rotated to the coordinate system where the x axis is the line joining the two points.

This doesn't seem like what you'd want for vectors.  Maybe <v1 . v2> and <|v1 x v2|>?  Just guessing here, since I don't know the science application, so maybe you have something else in mind.  And indeed, those two (fairly natural) combinations don't require and coordinate system change, since they are valid in any coordinate system.

**Comment by smsharma** [comment]
Thank you for the quick response!

Ideally, the correlation would be between vectors projected onto the plane perpendicular to the line-of-sight from the Earth's position. This is because velocities are most accurately measured in this transverse plane. This would then yield two independent components for the correlation function.

**Comment by rmjarvis** [comment]
I don't think you understood my question.  I was already assuming that the input data would be 2 transverse velocities (let's call them v_ra and v_dec) and one radial velocity (v_r).  Fine to leave out the radial velocity if you want.

But once you have a given pair of velocities for two stars at different positions, what exactly are the products you want TreeCorr to calculate and accumulate as a function of the separation distance?

Presumably not just v_ra1 * v_ra2, v_ra1 * v_dec2, v_dec1 * v_ra2, v_dec1 * v_dec2.  If you wanted those, you would just use KKCorrelation, which is already in TreeCorr.

I assume you want some kind of projection of the velocities relative to the line joining the two stars.  E.g. for a pair of stars along the equator, v_ra1 * v_ra2 means the same thing as v_dec1 * v_dec2 for a pair oriented along a meridian.  I.e. the product of the velocity components towards or away from each other.

So it would help if you described exactly what kind of information you want the VVCorrelation function to accumulate for the pairs of stars being correlated.

**Comment by smsharma** [comment]
Sorry---I definitely misunderstood your question! Yes, accumulating the quantities you mentioned (product of velocities along the line-of-sight and perpendicular to it) would be ideal for our application.

**Comment by rmjarvis** [comment]
Sorry for the long delay, but I've finally implemented this.  #158
