### ISSUE TITLE
Merging 2 fits catalog with TreeCorr

### ISSUE THREAD

**Issue by WF13** [rmjarvis/TreeCorr#83]
Hello,
I wanted to merge 2 fits cataloges with TreeCorr and compute shear shear correlation function,
Could you please help me how can I merge them?

**Comment by rmjarvis** [comment]
I don't know what you mean by merge.  Are the columns the same in both, but you want to include rows from both?  Or do you want to take some columns from one and other columns from the other.

Nor do I know how you are trying to run TreeCorr.  Are you using a config file with the corr2 executable?  Or calling things from python?

**Comment by WF13** [comment]
Yes, the columns are the same, and I want to include rows from both.
Yes, I am using a config file.

**Comment by rmjarvis** [comment]
Then it's super easy.  Just list both files in a list for the `file_name`.

cf. https://github.com/rmjarvis/TreeCorr/blob/releases/3.3/sample_config.yaml#L37

**Comment by WF13** [comment]
I actually did that before but I get an error,

I want to run the following code:

file_name:['KiDS_DR3.1_G9_ugri_shear.fits', 'KiDS_DR3.1_G12_ugri_shear.fits']
cat = treecorr.Catalog(file_name, ra_col='RAJ2000', dec_col='DECJ2000', ra_units='deg', dec_units='deg', g1_col='e1',g2_col='e2')
print(cat)

Error:
 expected str, bytes or os.PathLike object, not list

**Comment by rmjarvis** [comment]
I thought you were using corr2 with a config file.  This is why I asked you how you were using TreeCorr.  

In the future, when you want to report a problem with using some code (any code, not just TreeCorr), you should post the actual code you are trying to run, what you got from it, and what you expected to get from it.  Otherwise you're just wasting the time of the person who will be trying to help you.

So, now to try to address your actual problem...

Catalog cannot take multiple files.  It takes one file.  cf. [its documentation](http://rmjarvis.github.io/TreeCorr/html/catalog.html)

However, you can pass multiple catalogs to `process`.  cf. [its documentation](http://rmjarvis.github.io/TreeCorr/html/gg.html#treecorr.GGCorrelation.process)

Please read the documentation for these function carefully, and if you still have problems, please post a complete code snippet that demonstrates your problem.
