### ISSUE TITLE
nosetests

### ISSUE THREAD

**Issue by jecampagne** [rmjarvis/TreeCorr#86]
Hi! I've just clone the repo on my laptop (Mac on Mojav).
After
python setup.py install
pip install -r test_requirements.txt
cd tests
nosetests
........Segmentation fault: 11

Running run_all_tests the crash is more explicit:
./run_all_tests: line 17: 27236 Segmentation fault: 11  $python test_catalog.py

**Comment by rmjarvis** [comment]
I need a bit more information to help here:

1. Does `python test_catalog.py` seg fault immediately, or does it produce any output that you didn't post?
2. If the former, then if you open a python session, does `import treecorr` already fail?
3. Do you maybe have other versions of TreeCorr installed on your machine?  Sometimes `python setup.py install` doesn't override `pip` installations.  So you may need to do `pip uninstall treecorr` repeatedly until there are none left, and then reinstall.

**Comment by jecampagne** [comment]
Hi! Sorry I have just see your answer right now (may be there is a way to be warned for answer..)
Ok Here is the output before I get Segmentation Fault 11
[test_catalog.txt](https://github.com/rmjarvis/TreeCorr/files/3111630/test_catalog.txt)
Thanks
JE

**Comment by rmjarvis** [comment]
You should check your GitHub notifications settings.  Normally it will email you with responses to issues you are participating it.  You may have that turned off.

Anyway, thanks for posting the full output.  Unfortunately there is a fair amount of testing between the last output you got and the next one that you didn't get.  So it's still hard to tell exactly what might be causing the Seg fault.

If you don't mind trying to diagnose this, could you please try the following commands:
```
nosetests -vs test_catalog:test_contiguous
nosetests -vs test_catalog:test_list
nosetests -vs test_catalog:test_write
nosetests -vs test_catalog:test_field
```
Then once you figure out which test function is failing, if you could add some print statements to that function to try to figure out exactly which line is failing, that might help give us a clue what the problem might be.

**Comment by jecampagne** [comment]
Hi!

> nosetests -vs test_catalog:test_contiguous
test_catalog.test_contiguous ... dtypes of original arrays:  [dtype('float64'), dtype('float64'), dtype('float32'), dtype('float128')]
dtypes of cat2 arrays:  [dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64')]
is original g2 array contiguous? False
is cat2.g2 array contiguous? True
ok

----------------------------------------------------------------------
Ran 1 test in 0.020s

OK
Segmentation fault: 11

For test_list and test_write Ok

For test_field there is no print
Segmentation fault: 11

JE

**Comment by jecampagne** [comment]
More input:

In the **test_field** the segmentation fault occurs line ~ 917:  
`nfield1 = cat1.getNField()`

For the **test_contiguous** the segmentation fault occurs after the function return !

JE

**Comment by rmjarvis** [comment]
Thanks.  I think that's the first place in the tests that tries to access the treecorr library file.  So my best guess at the moment is that there is something wrong with how you installed it.  Could you please try recompiling from scratch, and post the full output that is printed to the screen:
```
/bin/rm -r build
python setup.py install
```

Then check what library file it is trying to use at run time.
```
cd tests
python -c "import treecorr; print(treecorr.lib_file); print(treecorr.__file__)"
```
The locations printed out in the last step should match up with the locations where the installation copied files.  If not, then that could explain the seg fault, since the call signature changed between TreeCorr 3.3 and 4.0, so if you somehow still have a 3.3 library being loaded, then that would be problematic.

Another thing you can check along these lines is the call signature of the BuldNField function:
```
python -c "import treecorr; print(treecorr._lib.BuildNField)"
```
The output should look like:
```
<cdata 'void *(*)(double *, double *, double *, double *, double *, long, double, double, int, int, int, int, int)' 0x108f83c90>
```
The final hex code might be different, but the signature for the parameters should match up.  (They changed somewhat for 4.0.)

**Comment by jecampagne** [comment]
Hi!
1) I have never download TreeCorr before so no 3.3/4.0 missmatch on my Mac :)
2) Now, after cleaning "build" and run the setup.py, then the command 
`python -c "import treecorr; print(treecorr.lib_file); print(treecorr.__file__)"`
gives
python -c "import treecorr; print(treecorr.lib_file); print(treecorr.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/campagne/anaconda3/lib/python3.7/site-packages/treecorr/__init__.py", line 42, in <module>
    _lib = _ffi.dlopen(lib_file)
  File "/Users/campagne/anaconda3/lib/python3.7/site-packages/cffi/api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Users/campagne/anaconda3/lib/python3.7/site-packages/cffi/api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Users/campagne/anaconda3/lib/python3.7/site-packages/cffi/api.py", line 797, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '/Users/campagne/anaconda3/lib/python3.7/site-packages/treecorr/_treecorr.cpython-37m-darwin.so': dlopen(/Users/campagne/anaconda3/lib/python3.7/site-packages/treecorr/_treecorr.cpython-37m-darwin.so, 2): Symbol not found: _GOMP_parallel
  Referenced from: /Users/campagne/anaconda3/lib/python3.7/site-packages/treecorr/_treecorr.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/campagne/anaconda3/lib/python3.7/site-packages/treecorr/_treecorr.cpython-37m-darwin.so.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/campagne/anaconda3/lib/python3.7/site-packages/treecorr/_treecorr.cpython-37m-darwin.so'

The same also for the 
`python -c "import treecorr; print(treecorr._lib.BuildNField)"`
command.

**Comment by rmjarvis** [comment]
OK.  This is helpful.  I'm not sure why it got past this before when you built treecorr, and not this time, but now it's not finding the correct openmp library at run time.  

This usually indicates that you have a mismatch between the compiler that your Python is using and the one you get on the command line.  Or possibly that your LD_LIBRARY_PATH doesn't include the directory where Anaconda has its libraries, so it's not finding the right libraries at run time.  

In particular here, TreeCorr compiled with -fopenmp to enable OpenMP because the compiler that setup.py found (Anaconda's compiler probably) can handle it.  But at run time, it's not finding the OpenMP library, presumably because your default compiler (and runtime library path) doesn't support it.  

Previously you weren't getting this for whatever reason, but it's possible a library mismatch is what was causing your seg faults as well.

So, my recommendation here, since you are using Anaconda python, is to use conda for installing TreeCorr as well, rather than installing it yourself.  This should make sure that all the paths and consistent between build and runtime.
```
conda install -c conda-forge treecorr
```

**Comment by jecampagne** [comment]
Great ! Three items below

Item 1:
-----
The conda installation seems to work:
nosetests -vs test_catalog:test_field
test_catalog.test_field ... 
coucou 1
coucou 2
coucou 3
nfield:  0.011471033096313477 1.9073486328125e-05
gfield:  0.003954887390136719 1.7881393432617188e-05
kfield:  0.0032529830932617188 1.71661376953125e-05
nsimplefield:  0.0013217926025390625 7.152557373046875e-06
gsimplefield:  0.001447916030883789 8.106231689453125e-06
ksimplefield:  0.00133514404296875 7.867813110351562e-06
after resize(3) nfield:  0.0022552013397216797 1.621246337890625e-05
values =  []
len(cache) =  3
after resize(0) nfield:  0.003857135772705078 0.004187822341918945
before garbage collection: cat1.field =  None
after garbage collection: cat1.field =  None
ok

----------------------------------------------------------------------
Ran 1 test in 0.073s

OK

Item 2
------
But just typing "nosetests", I get an error:
nosetests
.....OMP: Error #15: Initializing libomp.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
Abort trap: 6

Item 3
------
A question if I have a "X, Y, Z" set of data (42 10^6 objects) in a DataFrame,  and I would like to compute w(theta): 1) is-it possible and 2) how should I proceed?

Thanks for your kind help
Jean-Eric

**Comment by rmjarvis** [comment]
1. Great!
2. Well, it looks like you still are having issues with respect to multiple compilers and/or multiple omp libraries.  You need to check you PATH, LD_LIBRARY_PATH, DYLD_LIBRARY_PATH, and maybe uninstall some of the conflicting things (e.g. maybe a brew installed gcc?).  Probably try Googling the error you are getting.  I found [this thread](https://github.com/dmlc/xgboost/issues/1715) with several suggestions you could try.
3. Yes.  Read through the [documentation](https://rmjarvis.github.io/TreeCorr/_build/html/index.html) and probably the [tutorial notebook](https://github.com/rmjarvis/TreeCorr/blob/master/tests/Tutorial.ipynb).

**Comment by jecampagne** [comment]
OK Thanks a lot. we can close the thread.
I will proceed to go through the doc/tuto of course.
JE

**Comment by rmjarvis** [comment]
Good.  Feel free to open back up if you have further issues that you think I could help with.
